// Guitar Chords — common open and barre chord shapes
// strings: [lowE, A, D, G, B, highE] — null=muted, 0=open, n=fret
// fingers: [lowE, A, D, G, B, highE] — 1=index, 2=middle, 3=ring, 4=pinky
// barres: [{ fret, fromString (0=lowE), toString }]
// baseFret: starting fret position (1 = nut)

const cards = [
  // ===== Level 1 — Open Major & Minor =====
  {
    word: "C Major",
    strings: [null, 3, 2, 0, 1, 0],
    fingers: [null, 3, 2, null, 1, null],
    baseFret: 1,
    level: 1,
  },
  {
    word: "D Major",
    strings: [null, null, 0, 2, 3, 2],
    fingers: [null, null, null, 1, 3, 2],
    baseFret: 1,
    level: 1,
  },
  {
    word: "E Major",
    strings: [0, 2, 2, 1, 0, 0],
    fingers: [null, 2, 3, 1, null, null],
    baseFret: 1,
    level: 1,
  },
  {
    word: "G Major",
    strings: [3, 2, 0, 0, 0, 3],
    fingers: [2, 1, null, null, null, 3],
    baseFret: 1,
    level: 1,
  },
  {
    word: "A Major",
    strings: [null, 0, 2, 2, 2, 0],
    fingers: [null, null, 2, 1, 3, null],
    baseFret: 1,
    level: 1,
  },
  {
    word: "A Minor",
    strings: [null, 0, 2, 2, 1, 0],
    fingers: [null, null, 2, 3, 1, null],
    baseFret: 1,
    level: 1,
  },
  {
    word: "D Minor",
    strings: [null, null, 0, 2, 3, 1],
    fingers: [null, null, null, 2, 3, 1],
    baseFret: 1,
    level: 1,
  },
  {
    word: "E Minor",
    strings: [0, 2, 2, 0, 0, 0],
    fingers: [null, 2, 3, null, null, null],
    baseFret: 1,
    level: 1,
  },

  // ===== Level 2 — More Open Chords & 7ths =====
  {
    word: "C Major 7",
    strings: [null, 3, 2, 0, 0, 0],
    fingers: [null, 3, 2, null, null, null],
    baseFret: 1,
    level: 2,
  },
  {
    word: "A7",
    strings: [null, 0, 2, 0, 2, 0],
    fingers: [null, null, 2, null, 3, null],
    baseFret: 1,
    level: 2,
  },
  {
    word: "D7",
    strings: [null, null, 0, 2, 1, 2],
    fingers: [null, null, null, 2, 1, 3],
    baseFret: 1,
    level: 2,
  },
  {
    word: "E7",
    strings: [0, 2, 0, 1, 0, 0],
    fingers: [null, 2, null, 1, null, null],
    baseFret: 1,
    level: 2,
  },
  {
    word: "G7",
    strings: [3, 2, 0, 0, 0, 1],
    fingers: [3, 2, null, null, null, 1],
    baseFret: 1,
    level: 2,
  },
  {
    word: "B7",
    strings: [null, 2, 1, 2, 0, 2],
    fingers: [null, 2, 1, 3, null, 4],
    baseFret: 1,
    level: 2,
  },
  {
    word: "A Minor 7",
    strings: [null, 0, 2, 0, 1, 0],
    fingers: [null, null, 2, null, 1, null],
    baseFret: 1,
    level: 2,
  },
  {
    word: "D Minor 7",
    strings: [null, null, 0, 2, 1, 1],
    fingers: [null, null, null, 2, 1, 1],
    barres: [{ fret: 1, fromString: 4, toString: 5 }],
    baseFret: 1,
    level: 2,
  },
  {
    word: "E Minor 7",
    strings: [0, 2, 0, 0, 0, 0],
    fingers: [null, 2, null, null, null, null],
    baseFret: 1,
    level: 2,
  },
  {
    word: "F Major",
    strings: [1, 1, 2, 3, 3, 1],
    fingers: [1, 1, 2, 3, 4, 1],
    barres: [{ fret: 1, fromString: 0, toString: 5 }],
    baseFret: 1,
    level: 2,
  },

  // ===== Level 3 — Barre Chords & Suspended =====
  {
    word: "B Minor",
    strings: [null, 2, 4, 4, 3, 2],
    fingers: [null, 1, 3, 4, 2, 1],
    barres: [{ fret: 2, fromString: 1, toString: 5 }],
    baseFret: 1,
    level: 3,
  },
  {
    word: "F# Minor",
    strings: [2, 2, 4, 4, 2, 2],
    fingers: [1, 1, 3, 4, 1, 1],
    barres: [{ fret: 2, fromString: 0, toString: 5 }],
    baseFret: 1,
    level: 3,
  },
  {
    word: "Bb Major",
    strings: [null, 1, 3, 3, 3, 1],
    fingers: [null, 1, 2, 3, 4, 1],
    barres: [{ fret: 1, fromString: 1, toString: 5 }],
    baseFret: 1,
    level: 3,
  },
  {
    word: "Asus2",
    strings: [null, 0, 2, 2, 0, 0],
    fingers: [null, null, 1, 2, null, null],
    baseFret: 1,
    level: 3,
  },
  {
    word: "Asus4",
    strings: [null, 0, 2, 2, 3, 0],
    fingers: [null, null, 1, 2, 3, null],
    baseFret: 1,
    level: 3,
  },
  {
    word: "Dsus2",
    strings: [null, null, 0, 2, 3, 0],
    fingers: [null, null, null, 1, 3, null],
    baseFret: 1,
    level: 3,
  },
  {
    word: "Dsus4",
    strings: [null, null, 0, 2, 3, 3],
    fingers: [null, null, null, 1, 2, 3],
    baseFret: 1,
    level: 3,
  },
  {
    word: "Esus4",
    strings: [0, 2, 2, 2, 0, 0],
    fingers: [null, 2, 3, 4, null, null],
    baseFret: 1,
    level: 3,
  },
  {
    word: "Cadd9",
    strings: [null, 3, 2, 0, 3, 0],
    fingers: [null, 2, 1, null, 3, null],
    baseFret: 1,
    level: 3,
  },
  {
    word: "G/B",
    strings: [null, 2, 0, 0, 0, 3],
    fingers: [null, 1, null, null, null, 3],
    baseFret: 1,
    level: 3,
  },

  // ===== Level 4 — Extended & Jazz =====
  {
    word: "Fmaj7",
    strings: [null, null, 3, 2, 1, 0],
    fingers: [null, null, 3, 2, 1, null],
    baseFret: 1,
    level: 4,
  },
  {
    word: "Gmaj7",
    strings: [3, 2, 0, 0, 0, 2],
    fingers: [3, 2, null, null, null, 1],
    baseFret: 1,
    level: 4,
  },
  {
    word: "Dm9",
    strings: [null, null, 0, 2, 1, 0],
    fingers: [null, null, null, 2, 1, null],
    baseFret: 1,
    level: 4,
  },
  {
    word: "Em9",
    strings: [0, 2, 0, 0, 0, 2],
    fingers: [null, 2, null, null, null, 1],
    baseFret: 1,
    level: 4,
  },
  {
    word: "A7sus4",
    strings: [null, 0, 2, 0, 3, 0],
    fingers: [null, null, 1, null, 3, null],
    baseFret: 1,
    level: 4,
  },
  {
    word: "C/G",
    strings: [3, 3, 2, 0, 1, 0],
    fingers: [3, 4, 2, null, 1, null],
    baseFret: 1,
    level: 4,
  },
  {
    word: "D/F#",
    strings: [2, null, 0, 2, 3, 2],
    fingers: [1, null, null, 2, 4, 3],
    baseFret: 1,
    level: 4,
  },
  {
    word: "Am9",
    strings: [null, 0, 2, 2, 1, 3],
    fingers: [null, null, 2, 3, 1, 4],
    baseFret: 1,
    level: 4,
  },
  {
    word: "E9",
    strings: [0, 2, 0, 1, 0, 2],
    fingers: [null, 2, null, 1, null, 3],
    baseFret: 1,
    level: 4,
  },
  {
    word: "G6",
    strings: [3, 2, 0, 0, 0, 0],
    fingers: [2, 1, null, null, null, null],
    baseFret: 1,
    level: 4,
  },

  // ===== Level 5 — Advanced Barre & Moveable Shapes =====
  {
    word: "C#m7",
    strings: [null, 4, 6, 4, 5, 4],
    fingers: [null, 1, 3, 1, 2, 1],
    barres: [{ fret: 4, fromString: 1, toString: 5 }],
    baseFret: 4,
    level: 5,
  },
  {
    word: "Eb Major",
    strings: [null, null, 1, 3, 4, 3],
    fingers: [null, null, 1, 2, 4, 3],
    baseFret: 1,
    level: 5,
  },
  {
    word: "Ab Major",
    strings: [4, 4, 6, 5, 4, 4],
    fingers: [1, 1, 3, 2, 1, 1],
    barres: [{ fret: 4, fromString: 0, toString: 5 }],
    baseFret: 4,
    level: 5,
  },
  {
    word: "Bbm",
    strings: [null, 1, 3, 3, 2, 1],
    fingers: [null, 1, 3, 4, 2, 1],
    barres: [{ fret: 1, fromString: 1, toString: 5 }],
    baseFret: 1,
    level: 5,
  },
  {
    word: "F#7",
    strings: [2, 4, 2, 3, 2, 2],
    fingers: [1, 3, 1, 2, 1, 1],
    barres: [{ fret: 2, fromString: 0, toString: 5 }],
    baseFret: 1,
    level: 5,
  },
  {
    word: "Cm",
    strings: [null, 3, 5, 5, 4, 3],
    fingers: [null, 1, 3, 4, 2, 1],
    barres: [{ fret: 3, fromString: 1, toString: 5 }],
    baseFret: 3,
    level: 5,
  },
  {
    word: "Dbmaj7",
    strings: [null, 4, 3, 1, 1, 1],
    fingers: [null, 3, 2, 1, 1, 1],
    barres: [{ fret: 1, fromString: 3, toString: 5 }],
    baseFret: 1,
    level: 5,
  },
  {
    word: "G#m",
    strings: [4, 4, 6, 6, 4, 4],
    fingers: [1, 1, 3, 4, 1, 1],
    barres: [{ fret: 4, fromString: 0, toString: 5 }],
    baseFret: 4,
    level: 5,
  },
];

export default {
  id: "guitar-chords",
  name: "Guitar Chords",
  description: "Common open, barre, and extended chord shapes",
  cardType: "chord",
  cards,
};
