/**
 * Generate guitar-chords.js from @tombatossals/chords-db
 * Run: node scripts/generate-chords.js
 */

const db = require('@tombatossals/chords-db/lib/guitar.json');

// Map of chords we want, organized by level
// Format: [key, suffix, displayName, level]
const CHORD_LIST = [
  // Level 1 — Open Major & Minor
  ['C', 'major', 'C Major', 1],
  ['D', 'major', 'D Major', 1],
  ['E', 'major', 'E Major', 1],
  ['G', 'major', 'G Major', 1],
  ['A', 'major', 'A Major', 1],
  ['A', 'minor', 'A Minor', 1],
  ['D', 'minor', 'D Minor', 1],
  ['E', 'minor', 'E Minor', 1],

  // Level 2 — 7ths & F Major
  ['C', 'maj7', 'C Major 7', 2],
  ['A', '7', 'A7', 2],
  ['D', '7', 'D7', 2],
  ['E', '7', 'E7', 2],
  ['G', '7', 'G7', 2],
  ['B', '7', 'B7', 2],
  ['A', 'm7', 'Am7', 2],
  ['D', 'm7', 'Dm7', 2],
  ['E', 'm7', 'Em7', 2],
  ['F', 'major', 'F Major', 2],

  // Level 3 — Barre & Suspended
  ['B', 'minor', 'B Minor', 3],
  ['Fsharp', 'minor', 'F#m', 3],  // was F#m — using C#m instead as common barre
  ['Bb', 'major', 'Bb Major', 3],  // Bb = A#/Bb
  ['A', 'sus2', 'Asus2', 3],
  ['A', 'sus4', 'Asus4', 3],
  ['D', 'sus2', 'Dsus2', 3],
  ['D', 'sus4', 'Dsus4', 3],
  ['E', 'sus4', 'Esus4', 3],
  ['C', 'add9', 'Cadd9', 3],
  ['F', 'minor', 'F Minor', 3],

  // Level 4 — Extended & Jazz
  ['F', 'maj7', 'Fmaj7', 4],
  ['G', 'maj7', 'Gmaj7', 4],
  ['D', 'm9', 'Dm9', 4],
  ['E', 'm9', 'Em9', 4],
  ['A', '7sus4', 'A7sus4', 4],
  ['A', 'm9', 'Am9', 4],
  ['E', '9', 'E9', 4],
  ['G', '6', 'G6', 4],
  ['C', '9', 'C9', 4],
  ['D', 'maj7', 'Dmaj7', 4],

  // Level 5 — Advanced Barre & Moveable
  ['Csharp', 'm7', 'C#m7', 5],
  ['Eb', 'major', 'Eb Major', 5],
  ['Ab', 'major', 'Ab Major', 5],
  ['Bb', 'minor', 'Bbm', 5],  // using Eb minor position
  ['Fsharp', '7', 'F#7', 5],  // using C#7
  ['C', 'minor', 'Cm', 5],
  ['Ab', 'minor', 'Abm', 5],
  ['F', '9', 'F9', 5],
];

// Key name mapping for lookup
const KEY_MAP = {
  'C': 'C', 'Csharp': 'Csharp', 'D': 'D', 'Eb': 'Eb',
  'E': 'E', 'F': 'F', 'Fsharp': 'Fsharp', 'G': 'G',
  'Ab': 'Ab', 'A': 'A', 'Bb': 'Bb', 'B': 'B',
};

function convertChord(key, suffix, displayName, level) {
  const keyChords = db.chords[key];
  if (!keyChords) {
    console.error(`Key not found: ${key}`);
    return null;
  }

  const chord = keyChords.find(c => c.suffix === suffix);
  if (!chord) {
    console.error(`Suffix not found: ${key} ${suffix}`);
    return null;
  }

  // Use first position (most common voicing)
  const pos = chord.positions[0];

  // Convert frets: -1 = muted (null), 0 = open, n = fret
  const strings = pos.frets.map(f => f === -1 ? null : f);

  // Convert fingers: 0 = no finger shown (null for open/muted), n = finger number
  const fingers = pos.fingers.map((f, i) => {
    if (f === 0) return null;
    return f;
  });

  // Convert barres
  const barres = pos.barres.map(fret => {
    // Find the range of strings this barre covers
    let fromString = 0;
    let toString = 5;
    for (let s = 0; s < 6; s++) {
      if (pos.frets[s] === fret) {
        fromString = s;
        break;
      }
    }
    for (let s = 5; s >= 0; s--) {
      if (pos.frets[s] === fret) {
        toString = s;
        break;
      }
    }
    return { fret, fromString, toString };
  });

  const result = {
    word: displayName,
    strings,
    fingers,
    baseFret: pos.baseFret,
    level,
  };

  if (barres.length > 0) {
    result.barres = barres;
  }

  return result;
}

// Generate all chords
const cards = [];
const errors = [];

for (const [key, suffix, displayName, level] of CHORD_LIST) {
  const chord = convertChord(key, suffix, displayName, level);
  if (chord) {
    cards.push(chord);
  } else {
    errors.push(`${displayName} (${key} ${suffix})`);
  }
}

if (errors.length > 0) {
  console.error('Failed to find:', errors.join(', '));
}

// Output as JS module
const output = `// Guitar Chords — sourced from @tombatossals/chords-db (MIT)
// Generated by scripts/generate-chords.js — do not edit manually
// strings: [lowE, A, D, G, B, highE] — null=muted, 0=open, n=fret
// fingers: [lowE, A, D, G, B, highE] — 1=index, 2=middle, 3=ring, 4=pinky
// barres: [{ fret, fromString (0=lowE), toString }]
// baseFret: starting fret position (1 = nut)

const cards = ${JSON.stringify(cards, null, 2)};

export default {
  id: "guitar-chords",
  name: "Guitar Chords",
  description: "Common open, barre, and extended chord shapes",
  cardType: "chord",
  cards,
};
`;

require('fs').writeFileSync('js/decks/guitar-chords.js', output);
console.log(`Generated ${cards.length} chords`);
